### ISSUE TITLE
Missing ch32v003fun-usb-bootloader.ld

### ISSUE THREAD

**Issue by Joshua-Ashton** [cnlohr/rv003usb#13]
Trying to build the `bootloader` project results in:

```
/usr/bin/../lib/gcc/riscv64-unknown-elf/12.2.0/../../../../riscv64-unknown-elf/bin/ld: cannot open linker script file ch32v003fun-usb-bootloader.ld: No such file or directory
```

I was not able to find this anywhere in the repos. I am guessing you forgot to commit it?

**Comment by Joshua-Ashton** [comment]
Oh, looks like this is there in the `new_usb_bootloader` branch. Nevermind then.

**Comment by cnlohr** [comment]
That reminds me - that needed to be merged.

**Comment by cnlohr** [comment]
(And now it is merged)
