### ISSUE TITLE
8 pin and 16 pin error

### ISSUE THREAD

**Issue by LenarOsx** [cnlohr/rv003usb#25]
I worked! its amazing, all examples worked but cdc, com port doesn't work.

I tried the code on ch32v003 over 8pin and 16pin version, with no luck. 
Is there a way to make it work on those versions, or is the code for the 20 pin version only?
Thanks.!

**Comment by cnlohr** [comment]
CDC doesn't work on Windows.

There were some recent changes where you can reconfigure it to use other pins.  It should work fine on other variants of the chip.

**Comment by LenarOsx** [comment]
I have downloaded the latest code, but it didn't work on 8 and 16 pin version, I found a specific configuration than kind of worked, port A, dm 2, dp 1. It does not show any error like 'invalid usb descriptor', it shows in usb device manager, but it does nothing.
no midi, no hid just shows correctly in the listed devices.

**Comment by cnlohr** [comment]
Are those ports reconfigurable? Also did you try swapping them?

**Comment by mcu23** [comment]
PC1, PC2, PC4  gamepad demo, Test OK.   

  usb_config.h

```
#define USB_DM 2
#define USB_DP 4
#define USB_DPU 1
#define USB_PORT C
```


![CH32v003_8pin_usb](https://github.com/cnlohr/rv003usb/assets/138208670/91a1161e-791f-4a46-9c0e-c646a0e80b08)

**Comment by cnlohr** [comment]
I have linked the above message in the README.  Closing issue now.  Thank you for testing.

**Comment by dienvx1997bn** [comment]
> PC1, PC2, PC4 gamepad demo, Test OK.
> 
> usb_config.h
> 
> ```
> #define USB_DM 4
> #define USB_DP 2
> #define USB_DPU 1
>  
> #define USB_PORT C
> ```

i design my own device but not work
#define USB_DM 2
#define USB_DP 4
#define USB_DPU 1
#define USB_PORT C

**Comment by cnlohr** [comment]
> > PC1, PC2, PC4 gamepad demo, Test OK.
> > usb_config.h
> > ```
> > #define USB_DM 4
> > #define USB_DP 2
> > #define USB_DPU 1
> >  
> > #define USB_PORT C
> > ```
> 
> i design my own device but not work #define USB_DM 2 #define USB_DP 4 #define USB_DPU 1 #define USB_PORT C

Please clarify - what errors are you receiving on the OS end?  Have you tested this with a known-good board configuration?  Please also share your schematic.  (And it probably makes sense to open a new ticket)

**Comment by dienvx1997bn** [comment]
> > > PC1, PC2, PC4 gamepad demo, Test OK.
> > > usb_config.h
> > > ```
> > > #define USB_DM 4
> > > #define USB_DP 2
> > > #define USB_DPU 1
> > >  
> > > #define USB_PORT C
> > > ```
> > 
> > 
> > i design my own device but not work #define USB_DM 2 #define USB_DP 4 #define USB_DPU 1 #define USB_PORT C
> 
> Please clarify - what errors are you receiving on the OS end? Have you tested this with a known-good board configuration? Please also share your schematic. (And it probably makes sense to open a new ticket)

Base on your suggestion design, and use ch32v003 sop8 chip
![image](https://github.com/cnlohr/rv003usb/assets/20875293/5a296b8d-2e31-4928-90ff-a76eb916f13d)

**Comment by cnlohr** [comment]
I have passed this issue off to some folks in my Discord.

**Comment by cnlohr** [comment]
I have passed this issue off to some folks in my Discord, a few who got the SOP-8 version working.  You may want to join that discord and see if they can help more.  I've never used the SOP-8 version of the 003. https://discord.gg/CCeyWyZ

I don't see any reason port C "shouldn't" work, but also, I don't have experience making it work.  Hopefully someone on the discord can shine some light.
