### ISSUE TITLE
does it need a quartz?

### ISSUE THREAD

**Issue by thirstyone** [cnlohr/rv003usb#50]
It is absent on your schematic. Will it work without a crystal? Or I shouldn't even try? In general, will it work on a ch32v003 in sop8 package?

**Comment by xsrf** [comment]
There is a schematic ;)
https://github.com/cnlohr/rv003usb?tab=readme-ov-file#it-requires-very-little-hardware

You do not need a crystal and it works with the SOP8. I use this configuration on two of my boards with the CH32V003J4M6:
```
PC1 D+
PC2 D-
PC4 D-_PU
```

**Comment by thirstyone** [comment]
Yep, I've seen the schematic. It's incredible that it doesn't need an external crystal! Thank you!

**Comment by cnlohr** [comment]
Just FYI - the reason it doesn't need a crystal is because it tunes the internal oscillator based on the SOFs (or SE0s)

**Comment by doragasu** [comment]
> Just FYI - the reason it doesn't need a crystal is because it tunes the internal oscillator based on the SOFs (or SE0s)

Oh, that could explain why it is **not** working when I enable HSE, maybe HSI is a requirement?

**Comment by cnlohr** [comment]
It is possible the HSI might be a requirement, since it uses the SOFs to retime the HSI.
