### ISSUE TITLE
PORT A for D+ D- Possible?

### ISSUE THREAD

**Issue by ATP-IOT** [cnlohr/rv003usb#55]
It's possible to use port A For the D+ and D- lines?
I'm using that port trying to free all the D and C GPIO pins

**Comment by ATP-IOT** [comment]
#define USB_PORT A     // [A,C,D] GPIO Port to use with D+, D- and DPU
#define USB_PIN_DP 1   // [0-4] GPIO Number for USB D+ Pin
#define USB_PIN_DM 2   // [0-4] GPIO Number for USB D- Pin
//#define USB_PIN_DPU 5  // [0-7] GPIO for feeding the 1.5k Pull-Up on USB D- Pin; Comment out if not used / tied to 3V3!

**Comment by cnlohr** [comment]
You got it working, right?  Close issue?

**Comment by NoNamedCat** [comment]
No, the device is not recognized by the system. I put a 1.5K resistor on the D- line but the OS throw me an error when I connect the device.

**Comment by cnlohr** [comment]
Do you have a logic analyzer you could use here to see what could be going on.  There's lots of possibilities that would cause issues, that may be totally unrelated.  I know other folks have a configuration like yours on port A.

**Comment by NoNamedCat** [comment]
I will try to make some experiments (change the GPIOs, the cable, the IC....) If nothing else work, I will use a digital logic analyzer. I don't have one, but i have access to one of those.
Tks a Lohr!

**Comment by cnlohr** [comment]
Totes recommend b-lining it to the scope capture so we can peek!  

Can you draw a full schematic?

**Comment by NoNamedCat** [comment]
![image](https://github.com/cnlohr/rv003usb/assets/39467683/093428d7-218c-4ba9-bbac-bae83442edd4)
![image](https://github.com/cnlohr/rv003usb/assets/39467683/0ab35555-b576-487e-a4da-be481a9f4e8a)
![image](https://github.com/cnlohr/rv003usb/assets/39467683/d1a9d9cf-9f0a-4bb4-bb1a-42f792457681)

**Comment by xsrf** [comment]
@NoNamedCat your USB signals are swapped on the USB connector. Your 1.5k pull-up is connected to D+ 😬

**Comment by NoNamedCat** [comment]
Tks! I will do the changes, and try again. Close this

**Comment by xsrf** [comment]
Now the pull-up is wrong - still connected to D+. The pull-up needs to be connected to D-/PA1

**Comment by NoNamedCat** [comment]
![image](https://github.com/cnlohr/rv003usb/assets/39467683/7d7829a5-595b-41b6-b9e0-22b85137fc94)
